apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubia-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
        version: "2.0"
    spec:
      containers:
      - name: kubia
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
          protocol: TCP
