apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: web2
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
          protocol: TCP
